# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package definition and TypeScript config
COPY package.json tsconfig.json ./
COPY src ./src

# Install dependencies and build
RUN npm install && npm run build

# Default command to run the MCP server
CMD ["node", "build/index.js"]